### ISSUE TITLE
[APF Odisha] Data Migration in Forms

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#171]
Data Migration from one from to another: APF team will inform the PS/Field Workers to not use the app for 1 week in which we can do all the data migration work

**Detailed analysis** - https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1604108639

- [ ] **Individual Registration to Pregnancy Enrolment::** Data of [two question](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=406612277&range=24:25)s needs to be migrated from this form **to Pregnancy Enrolment Form**. In case a women is enrolled multiple times into the Pregnancy Program, we need to take the latest data of the women for migration.

- [ ] **Pregnancy enrolment to ANC Form** [Field](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=893561151&range=18:18) “Mamata Scheme Amount received” is moved from Pregnancy enrolment form ->> ANC form. 

- [ ] **Delivery Form to PNC Form**: [One question](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=1368760264&range=20:20) from the Delivery form need to be migrated to the PNC form. Logic: Migrate that data, if in the Delivery Form, answer "Yes" is selected in the question Eligible for JSY Scheme? 
- [ ] **QRT Child:** : [One question ](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=142552483&range=26:26)needs to be changed and the data needs to be migrated to newly added advice question. The question " Reffered to NRC?" is removed and a new question is added "Advice" . So all the "Yes" option selected in the "Refer to NRC" question, now needs to be shown as " Refered to NRC" under the Advice question
