### ISSUE TITLE
APF | Sync Strategy Changes  Checklist

### ISSUE THREAD

**Issue by Parth7223** [avniproject/apfodishanutrition#183]
**Sync concept related changes**

- [x] Rename current "High Risk" sync concept to "To be monitored by QRT"
- [x] Update the same in all the decision rules
- [x] Update the same in both the program summary rules
- [x] Update/Check the same under Subject sync attribute

**Sync attribute based user group permission changes**

- [x] Refer the "Schedule For" column [here](https://docs.google.com/spreadsheets/d/1icrexwzKnBsSiaMrFq7B8Kd_aqIeg72KW4j29PCI5zI/edit#gid=2036643668&range=F1) and update the permissions in the respective user groups accordingly.

- [x] Test the complete flow of the app using a Poshan Sathi user and a QRT user under same catchment
 
## QA Checklist
- [x] Visits scheduled for QRT should be be view only to Poshan Sathi and vice versa
- [x] Records marked with "To be monitored by QRT" should only sync to QRT user's device and not any other visit

**Comment by Dinesh2019** [comment]
- [ ] If we cancel the old QRT and sync it getting the association error 10 

<img width="372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXg5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d5b346e097be738f16708d519cf21824605912b/Screenshot%202024-04-22%20at%2010.53.45%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 10.53.45 AM.png" />

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 please share the username that u r using

**Comment by Dinesh2019** [comment]
User name : dineshqrt@apfodishauat
pass : dine7988

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 This card can be tested on pre release APF Odisha org. UAT org on prod has data has old data which does not have proper sync concept data assosciated.

**Comment by Dinesh2019** [comment]
In pre-release also we are facing the same issues as per the new logic if delivery is completed then we are move out of QRT but old data still shows in the QRT.

Indi name : Pramila Nayak

Poshan user : poshan@apfodisha
pass : posh9999

QRT user : qrtu@apfodisha
pass : qrtu9999
