### ISSUE TITLE
{APF Dashboard Report}: Move the phase 2 reports from Prerelease to production.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/apfodishanutrition#216]
### Add below query :

```
set role apfodisha;

set search_path = public;

CREATE OR REPLACE FUNCTION contains_coded_values(array1 text[], string2 text) RETURNS boolean
AS $$
BEGIN
    RETURN NOT EXISTS (
        SELECT 1 FROM unnest(array1) element WHERE element NOT IN (SELECT unnest(string_to_array(string2, ', ')))
    );
END;
$$ LANGUAGE plpgsql;

```

Move all the below mentioned reports from pre-release to production:

**Tasks:**

- [x] Update datasets to point to prod instead of pre release
- [x] Update datasets created for filters to point to prod instead of pre release
- [x] Thoroughly test each report and rename them to exclude Pre release 
- [x] Set [row level security](https://docs.google.com/spreadsheets/d/10FaC3smIaDJk1UgSKlqwdHRj-tfOYQsXlua_m48A4ok/edit?gid=0#gid=0)

**Phase 2: New Reports**

- [ ] Trimester Wise PW Registration
- [ ] Mamata
- [ ] Delivery Details
- [ ] Delivery Location
- [ ] ANC Details
- [ ] EDD vs Actual Delivery
- [ ] EDD Timegap
- [ ] ANC done for PW
- [ ] PW Home Visits
- [ ] PNC Visits
- [ ] PW QRT
- [ ] Household Entitlements
- [ ] Clinically High Risk Pregnant Women
- [ ] Child Timeline
- [ ] Child Entitlement
- [ ] SAM Child Referral
- [ ] MAM Child Referral
- [ ] SAM & MAM Child Referral
- [ ] GF2 Child Referral
- [ ] Children Status
- [ ] Children Attended VHND
- [ ] All Vaccination Report
- [ ] Full vs Complete Vaccination

---
## Tech Notes:
Reference Document of Previous go Live : [Link](https://drive.google.com/drive/folders/1nM2xRy7NOUbR9ObgTBWF9tSbgEVCAYbe)
 
Roles and Row Level Security: 

1. For APF Odisha, As per end-user requirements. We created roles at Block/Project-Block level. So when users see the dashboard they are able to see only their respective roles level data.

2. For a new dataset if we want to apply row level security, we have to add it into appropriate row level security.

For example : 

If the dataset has only a village level hierarchy then we have to add it into “Block” = ‘<block_name>’.

If the dataset has only an AWC level hierarchy then we have to add it into “Project/Block” = ‘<project/block_name>’.

If the dataset has both hierarchies then we have to add it into "Block" = ‘<block_name>’ or "Project/Block" = '<project/block_name>' .

3. If the filter uses any hierarchy then we can apply row level security to that also.

4. If the dataset does not require rls and it shows error in the dashboard then directly add to roles.

**Comment by adamsanadi6** [comment]
@kameshbhariya I have moved the following reports from Prerelease to Production:
- [x] [Phase 2][APF Odisha] Trimester Wise PW Registration
- [x] [Phase 2][APF ODISHA] PNC VISITS [New]
- [x] [Phase 2][APF Odisha] EDD Vs Actual Delivery
- [x] [Phase 2][APFODISHA] SAM & MAM Child Referral
- [x] [Phase 2][APFODISHA] PW Home Visit Details
- [x] [Phase 2][APF Odisha] All Vaccination Report
- [x] [Phase 2][APFODISHA] Full vs Complete Vaccination
- [x] [Phase 2][APF Odisha] Child Timeline
- [x] [Phase 2][APFODISHA] Children Attended VHND
- [x] [Phase 2][APFODISHA] Children Status
- [x] [Phase 2][APFODISHA] GF2 Child Referral
- [x] [Phase 2][APFODISHA] MAM Child Referral
- [x] [Phase 2][APFODISHA] SAM Child Referral
- [x] [Phase 2][APFODISHA] Children Entitlement
- [x] [Phase 2][APF Odisha] Clinically High Risk Pregnant Women
- [x] [Phase 2][APFODISHA] Household Entitlements
- [x] [Phase 2][APFODISHA] PW QRT Visit
- [x] [Phase 2][APF Odisha] ANC done for PW women
- [x] [Phase 2][APF Odisha] EDD Timegap
- [x] [Phase 2][APFODISHA] Delivery Details
- [x] [Phase 2][APFODISHA][NEW] Delivery Location
- [x] [Phase 2][APFODISHA][NEW] ANC DETAILS
- [x] [Phase 2][APFODISHA]Sector-wise Distribution of Women Availed Benefits Under Mamta

**Comment by adamsanadi6** [comment]
**List of Datasets:**
1. [APFODISHA] Household Entitlements
2. [APFODISHA] - Child Referral
3. All Vaccination
4. [APF Odisha] Full vs Complete Vaccination
5. apfodisha pnc visits
6. mamta
7. anc details
8. Delivery Details
9. [APF odisha] EDD timegap
10. [APF Odisha] ANC done by PW
11. qrt visits
12. [APF Odisha] Clinically High Risk Pregnant Women
13. [APFODISHA] - Child Entitlement
14. [APFODISHA] - Children Status
15. [APFODISHA] - Children Attended VHND
16. pw home visits
17. [APF Odisha] EDD vs Actual Delivery
18. [APFODISHA] PW Registration Sector Wise
