### ISSUE TITLE
APF : Setting Up New UAT Org and Separating APF Dev Org

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#338]
**On UAT**

- [ ] rule failure --#320--done
- [ ] re-write high risk rule --#311-- done
- [ ] Growth Faltering not working in a particular scenario --#321 --already on prod

**On DEV**
 

- [ ] unplanned visit -- #324
- [ ] ANC Form: QRT Scheduling logic for Severe Anemic Case,#309
