### ISSUE TITLE
[APF Odisha Phase 2]: Prod Bug fixes - Batch 6: Moved to Production

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#433]
- [ ] Below bug fixes to be moved to Production 
- [x] Card: [[APF Odisha] Bug fix - Height/Weight autopopulating in a QRT visit gets updated from the latest visit in Edit scenario as well#429](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/429)
- [x] Card:[ [APF Odisha] Bug fix - Growth monitoring that is scheduled post cancellation schedules a Growth Monitoring with 2 days overdue#430](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/430)
- [ ] Card: [[APF Odisha] Bug fix - Age is less than 18’ and ‘Age is greater than 36’ should be added to the high-risk indicator#428](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/428)

****Not Part of this card** (Do Not Move the below fix to Production)**

- [ ] [APF rule failure](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/432)

**Comment by dinesh2096** [comment]
- [ ] Card 1 is not tested in prod since it needs the sync 

**QA Refrences :** 

[Click here to watch the video](https://drive.google.com/file/d/1R4gYcKrTZ4E7BjvAYfHjhs2I3dCCHlev/view?usp=drive_link)
