### ISSUE TITLE
APF Odisha Phase 2| Production Bug Fix: Batch 7 EPIC

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#447]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/apfodishanutrition/issues/445
- [ ] https://github.com/avniproject/apfodishanutrition/issues/444
- [ ] https://github.com/avniproject/apfodishanutrition/issues/440
- [ ] https://github.com/avniproject/apfodishanutrition/issues/446
- [ ] https://github.com/avniproject/apfodishanutrition/issues/439
- [ ] https://github.com/avniproject/apfodishanutrition/issues/422
- [ ] https://github.com/avniproject/apfodishanutrition/issues/448
- [ ] https://github.com/avniproject/apfodishanutrition/issues/450
```
