### ISSUE TITLE
APF Odisha Phase 2: Production Bug Fix | Batch 7: Changes to be moved to Production

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#450]
- [ ] Move the below changes made in APF UAT to APF Production 
- [ ] [Production Bug Fix Batch 7 Card #449](https://github.com/avniproject/apfodishanutrition/issues/449)
- [ ] [Production Bug Fix Batch 7 Card #448](https://github.com/avniproject/apfodishanutrition/issues/448)
- [ ] [Production Bug Fix Batch 7 Card #445](https://github.com/avniproject/apfodishanutrition/issues/445)
- [ ] [Production Bug Fix Batch 7 Card #444](https://github.com/avniproject/apfodishanutrition/issues/444)
- [ ] [Production Bug Fix Batch 7 Card [#422](https://github.com/avniproject/apfodishanutrition/issues/422)
