### ISSUE TITLE
APF Odisha Phase 2: Production Bug Fixes Batch 8 : EPIC

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/apfodishanutrition#451]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/apfodishanutrition/issues/422
- [ ] https://github.com/avniproject/apfodishanutrition/issues/432
- [ ] https://github.com/avniproject/apfodishanutrition/issues/440
```
