### ISSUE TITLE
[APF] Child Program & Vaccination Checklist

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/apfodishanutrition#5]
- [x] Create a program - "Child" 

- [x] Child enrolment form requirement-
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=23097314

- [x] Child exit form requirement -
https://docs.google.com/spreadsheets/d/1zNLwN9vb-ZGpnXKh3yk68bn_B9EmZR7YZgIkRpocUCQ/edit#gid=1798492401

- [x] Add Vaccination checklist and checklist rule from any other existing org.

**Comment by Gojo-Taqi** [comment]
ETC - 20 min
