### ISSUE TITLE
Move Report to Production

### ISSUE THREAD

**Issue by vedfordev** [avniproject/apfodishanutrition#89]
#### Report/Dashboard List :

- [Relapse Report(Village) - Aggregate](https://reporting-superset.avniproject.org/superset/dashboard/69/?native_filters_key=4RjD45Sfj-_AK7Sxs3jblpTnUMAq4mrQCKIRKD5eAQlsFsiU801h4AdOw8NrrhG1)
- [Relapse Report(AWC) - Aggregate](https://reporting-superset.avniproject.org/superset/dashboard/70/?native_filters_key=8jBHw7LEG5lgJCpIJoz2MDrki_3wOZYGDtr4Vm7M6O695th3rYKV1z7H-7bAv925)
- [Relapse Report - LineList[ APFODISHA ] Relapse Report - LineList](https://reporting-superset.avniproject.org/superset/dashboard/71/?native_filters_key=EYtAuTTHeYShBHp2D4fGljI8kx2cpnLbZCzNjVkP3M7g2aBthD8MshIJMFv-_WDI)

#### Dataset Used :

- apfodisha relapse aggregate village (Relapse Aggregate (Village))
- apfodisha relapse aggregate awc (Relapse Report(AWC) - Aggregate)
- apfodisha relapse linelist([ APFODISHA ] Relapse Report - LineList)
- apfodisha Year(Year)

#### Task for developer :

- [x] Change dataset query to prod
- [x] Add roles to dashboard
- [x] Take reference of older report and provide row level security
- [ ] If possible then try to remove error message

**Comment by vedfordev** [comment]
## Developer's Note:

#### Dev Testing:
1. Assigned my user role and checked above report.
2. Try with providing filter value Year as 2023 and month march.

**Comment by Dinesh2019** [comment]
- [ ] 	[APFODISHA] Relapse Report(Village) - Aggregate - apfodishagramma role - getting the unexcpeted error

**Comment by salilsamanvay** [comment]
@sachsk as per our discussion, below points are to be resolved for all the 3 reports:
1. reports is showing an error on the main page due to time range not selected, which is not required as per requirement.
2. current month report should be shown by default when the user opens this report, currently this is not working.

**Comment by vedfordev** [comment]
@sachsk @salilsamanvay  we can provide default month and year.
https://www.youtube.com/watch?v=qGfzcRMykbc
