### ISSUE TITLE
APF issues fix

### ISSUE THREAD

**Issue by sachsk** [avniproject/apfodishanutrition#95]
- [x] 1. Gender missing - populate through script now and monitor.  https://avni.freshdesk.com/a/tickets/3020 [Alert link](https://reporting.avniproject.org/question/2613-individuals-with-missing-gender)
-----------------------------------------------------------------------------------------------------------------------
- [x] 2. Duplicate individuals to be merged  https://avni.freshdesk.com/a/tickets/3113 [Alert link] Closed the ticket for now (https://reporting.avniproject.org/question/2649-duplicate-individuals)
-----------------------------------------------------------------------------------------------------------------------
- [x] 3. Household and individual address difference  https://avni.freshdesk.com/a/tickets/3114 [Alert link] Closed the ticket for now (https://reporting.avniproject.org/question/2645-individuals-and-households-having-different-address)
-----------------------------------------------------------------------------------------------------------------------
- [x] 4. App restart error [No ticket available]
-----------------------------------------------------------------------------------------------------------------------
- [x] 6. Association error [Investigation on going]
-----------------------------------------------------------------------------------------------------------------------
- [x] 7. Data fix [Card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/102)
-----------------------------------------------------------------------------------------------------------------------
- [x] 8. Slow sync (QRT) https://avni.freshdesk.com/a/tickets/3115
-----------------------------------------------------------------------------------------------------------------------
- [x] 9. Not Syncing and White screen. https://avni.freshdesk.com/a/tickets/3098
-----------------------------------------------------------------------------------------------------------------------
- [x] 10. QRT user sync issue. https://avni.freshdesk.com/a/tickets/2941
-----------------------------------------------------------------------------------------------------------------------
- [x] 11. Report showing different numbers  https://avni.freshdesk.com/a/tickets/2954 [Alert link](https://reporting.avniproject.org/question/2641-apf-individuals-who-are-registered-in-awc-heirarchy)
[Product Ticket](https://avni.freshdesk.com/a/tickets/3161)
-----------------------------------------------------------------------------------------------------------------------
- [x] 12. Visit scheduling bug [Fixed]
-----------------------------------------------------------------------------------------------------------------------
- [x] 13. load is high on Read DB used by Superset reports https://avni.freshdesk.com/a/tickets/3050
-----------------------------------------------------------------------------------------------------------------------

- [x] 14. Summary and Status showing different https://avni.freshdesk.com/a/tickets/2932
-----------------------------------------------------------------------------------------------------------------------
- [x] 15. Remove vaccination permissions for all QRT (need testing) [Card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/99)
-----------------------------------------------------------------------------------------------------------------------
- [x] 16. Slow dashboards [[Card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/apfodishanutrition/80)]
